// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	deleteCategory(ctx context.Context, id int32) error
	getCategories(ctx context.Context, arg getCategoriesParams) ([]Category, error)
	getCategory(ctx context.Context, id int32) (Category, error)
	getUser(ctx context.Context, username string) (User, error)
	getUserById(ctx context.Context, id int32) (User, error)
	updateCategory(ctx context.Context, arg updateCategoryParams) (Category, error)
}

var _ Querier = (*Queries)(nil)
